// Generated by FlutterFire CLI and tied to the poise-69f8f Firebase project.
// I'm reusing the same Firebase project from the POC -- same backend, clean frontend.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run the FlutterFire CLI again to add it.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFHL0FWGGR395vL52t_CVQJre3SsxRlMY',
    appId: '1:848689202046:web:8709d9c205d51b254b692f',
    messagingSenderId: '848689202046',
    projectId: 'poise-69f8f',
    authDomain: 'poise-69f8f.firebaseapp.com',
    storageBucket: 'poise-69f8f.firebasestorage.app',
    measurementId: 'G-8TT2FPQT15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASbXXyOEqCYPKSRZh27tIJukqDZ9cLpPA',
    appId: '1:848689202046:android:6944a680cc92ebb54b692f',
    messagingSenderId: '848689202046',
    projectId: 'poise-69f8f',
    storageBucket: 'poise-69f8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU8QsQlxF7qkk8NfBrg4ZKlZMsEoGpUOM',
    appId: '1:848689202046:ios:eabb3617ffee2f0c4b692f',
    messagingSenderId: '848689202046',
    projectId: 'poise-69f8f',
    storageBucket: 'poise-69f8f.firebasestorage.app',
    iosBundleId: 'com.kierankinnaird.poise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU8QsQlxF7qkk8NfBrg4ZKlZMsEoGpUOM',
    appId: '1:848689202046:ios:eabb3617ffee2f0c4b692f',
    messagingSenderId: '848689202046',
    projectId: 'poise-69f8f',
    storageBucket: 'poise-69f8f.firebasestorage.app',
    iosBundleId: 'com.kierankinnaird.poise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFHL0FWGGR395vL52t_CVQJre3SsxRlMY',
    appId: '1:848689202046:web:c603b04d5aea123b4b692f',
    messagingSenderId: '848689202046',
    projectId: 'poise-69f8f',
    authDomain: 'poise-69f8f.firebaseapp.com',
    storageBucket: 'poise-69f8f.firebasestorage.app',
    measurementId: 'G-EVENDMPZMY',
  );
}
